require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
